name: Build MAUI App
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest  # usa una VM Windows
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Install MAUI workload
        run: dotnet workload install maui

      - name: Build Android project
        run: dotnet build MauiApp1/MauiApp1/MauiApp1.csproj -c Release -f net9.0-android
      
      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: MauiApp-Android
          path: '**/bin/Release/net9.0-android/*.apk'

